env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"
    - SYMFONY_VERSION="2.5.*"

language: php
php:
    - 5.5
    - 5.4
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update

before_script:
    touch app/bootstrap.php.cache

script:
    ./bin/phpunit -c app/ --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover